language: csharp
dist: xenial
mono: none
dotnet: 2.2.105
before_install:
  - sudo apt-get update && sudo apt install -y doxygen
script:
  - dotnet restore
  - dotnet build -c Release
  - doxygen Doxyfile
  - touch docs/html/.nojekyll
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $GH_REPO_TOKEN
    on:
      branch: develop
  - provider: releases
    skip_cleanup: true
    api_key: $GH_REPO_TOKEN
    file_glob: true
    file:
      - "Oddity/bin/Release/Oddity.*.nupkg"
    on:
      tags: true
      branch: master
  - provider: script
    skip_cleanup: true
    file_glob: true
    script: dotnet nuget push "Oddity/bin/Release/Oddity.*.nupkg" -k $NUGET_KEY -s $NUGET_SOURCE --no-symbols
    on:
      tags: true
      branch: master
notifications:
  email: false